# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

android_library(
  name = 'lib',
  srcs = glob(['*.java']),
  resources = glob([
      'resources/**',
  ]),
  resources_root = 'resources',
  deps = [
    '//android/resources:res',
    '//android/cxx:jni',
    ':libphone',
  ],
  visibility = [
    '//android:demo-app',
  ],
)

prebuilt_jar(
  name = 'libphone',
  binary_jar = 'libphonenumber.jar',
)

project_config(
  src_target = ':lib',
)
