# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

java_binary(
    name = "hello-buck-java",
    main_class = "com.facebook.buck.demo.HelloBuckJava",
    deps = [":main"],
)

java_library(
    name = "main",
    srcs = glob(["*.java"]),
)
