# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

apple_resource(
  name = 'BuckDemoAppResources',
  files = glob(['*.png']),
  dirs = [],
)

apple_bundle(
  name = 'BuckDemoApp',
  binary = ':BuckDemoAppBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  tests = [':BuckDemoAppTest'],
)

apple_binary(
  name = 'BuckDemoAppBinary',
  deps = [':BuckDemoAppResources', '//common:hello'],
  preprocessor_flags = ['-fobjc-arc', '-Wno-objc-designated-initializers'],
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.m',
    '*.swift',
  ]),
  swift_objc_bridging_header = 'BuckDemoApp-Bridging-Header.h',
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
  ],
)

apple_package(
  name = 'BuckDemoAppPackage',
  bundle = ':BuckDemoApp',
)

apple_test(
  name = 'BuckDemoAppTest',
  extension = 'xctest',
  test_host_app = ':BuckDemoApp',
  srcs = ['tests/BuckDemoAppTest.m'],
  info_plist = 'tests/Test.plist',
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
  ],
)
