cxx_binary(
  name = 'main',
  srcs = [
    'hello-buck.cxx',
  ],
  deps = [
    ':hello_string',
  ],
  default_platform="zuck"
)

cxx_library(
  name = 'hello_string',
  srcs = [
    'hello-string.cxx',
  ],
  headers = [
    'hello-string.h',
  ],
)

