# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

java_library(
  name = 'dummy_java_for_buck_project',
)

project_config(
  src_target = ':dummy_java_for_buck_project'
)
